[project]
name = "yt-data-collector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-api-python-client>=2.154.0",
    "youtube-transcript-api>=0.6.3",
]
